### ISSUE TITLE
particles outside the MPI domains 

### ISSUE THREAD

**Issue by jegarfa** [pelahi/VELOCIraptor-STF#112]
Hi @pelahi,

I am using VELOCIraptor to indentify halos from a COLA simulation (snapshots are in gadget format).
Initially, I used velociraptor in a test simulation (128^3 particles in a 1Gpc box). The halos were identified successfully, and I did not encounter any errors. However, when using a larger simulation (2048^3 particles in a 1Gpc box), I encountered the following error:

```
Task 31 has particles outside the MPI domains of every process (986.33, 1000, 951.169).
```

I noticed that "31" refers to the number of the MPI task, but I still received this error even when changing the number of MPI tasks. I am wondering if this error is related to particles close to the boundaries and if there is a workaround?. Have you face a similar error in the past? As for the rest, I believe that the gadget binaries are being read correctly, as I checked the output.siminfo.

Thank you in advance,

**Comment by pelahi** [comment]
Hi @jegarfa , do you mind trying the https://github.com/pelahi/VELOCIraptor-STF/tree/feature/codecleanup-icrar branch? It has lots of improvements and so might help track down the issue a bit better. This branch will soon be the main branch.

**Comment by jegarfa** [comment]
Hi @pelahi, with the new brach the compilation fail. I got incompatibility with the NBodyLib version.
After cloning the repository and check it out to the  codecleanup-icrar branch I made `git submodule update --init --recursive`
 and `git submodule update --recursive --remote`. However I got:

CMake Error at cmake/VRCMakeUtils.cmake:227 (message):
  NBodyLib version 1.28 unsupported,

      		VELOCIraptor requires >= 1.30

So I manually update NBodyLib to 1.30 from the git repository, it pass the `cmake`, but I got error when building: 

```
/home/user/VELOCIraptor-STF/src/mpigadgetio.cxx:108:5: error: expected ‘;’ before ‘if’
/home/user/VELOCIraptor-STF/src/mpigadgetio.cxx:111:9: error: ‘MPIDomainDecompositionGagdet’ was not declared in this scope
         MPIDomainDecompositionGagdet(opt);
```

**Comment by pelahi** [comment]
ah, oops sorry. Don't commit in a hurry is the lesson. I did a quick update and did not check to see if it built. Now fixed :)

**Comment by jegarfa** [comment]
Great! I confirm that now it compiles :)
However, the error persists. With the new branch I got the same error after a couple of minutes of execution: 

```
Task 63 has 0.0625 of the volume
63 has particle outside the mpi domains of every process (971.091,1000,928.095)
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 63 in communicator MPI_COMM_WORLD
with errorcode 9.
```

It wrote the files .configuration, .siminfo and .units. 
can it be related to precision of the particle position? since the number of particles is very high, perjaps some particles fall outside the domains¿? (I am not 100% sure). I checked that the snap were no corrupted, I can read them and plot them with no problem.  Would be possible to check if the particles falls in its domain or to keep only those particles? any advice?

thanks,

**Comment by pelahi** [comment]
Hi @jegarfa so is the period (and hence the limits of the mpi decomposition) being read correctly? Is the particle that is outside the range expected to have a value of exactly 1000? Guess you could increase the precision at which the output is placed but not certain that is very informative. 

I guess the question is what is the accuracy of the positions? Note VELOCIraptor has been run on ~6000^3 dm simulations with particle positions stored and read as doubles without this type of issue. 

Could it be that the periodic wrapping on particle positions hasn't been applied before saving the data? In that case, with positions actually being outside the periodic domain, I've updated the code so that you can built it to wrapper particles beyond the period domain. I've just added this commit to this branch so you can git pull. Note I haven't tested it yet but will get to it soon. 

Just need to run cmake with a new option
```bash
cmake -DVR_PARTICLES_OUTSIDE_PERIOD_LIMIT=ON ...
```

That should then wrap particles so that they are in the periodic domain that sets the MPI limits. Do you mind trying this update?

**Comment by jegarfa** [comment]
Hi @pelahi, thank you for the update. 

I cross-checked and the period is being read correctly, also the mesh decomposition seems to be fine.
From the output.siminfo I got a Lbox=999.9995004. 

```
ScaleFactor : 0.666667 # float64 
h_val : 0.676600 # float64 
Omega_m : 0.311100 # float64 
Omega_Lambda : 0.688900 # float64 
Omega_cdm : 0.311100 # float64 
Omega_b : 0.000000 # float64 
w_of_DE : -1.000000 # float64 
Period : 985.318751 # float64 
```

I think it's likely that the periodic wrapping on the positions was not applied before writing the snapshots. However, I could not identify any particles outside the range; in fact, I found all particles inside. I've checked the data type, and both particles and velocities were written as double, so this should not be a problem. This is what I have tried so far with the new update:

**A.** When compiled with `-DVR_PARTICLES_OUTSIDE_PERIOD_LIMIT=ON` it seems that **stf** looks for hdf5 files even when gadget format is specified. So I got error of reading the files:
```
[0000] [   8.228] [error] h5_utils.cxx:_hdf5_error_handler:L19 Error in HDF routine H5Fopen, aborting

  #008: H5FDsec2.c line 352 in H5FD__sec2_open(): unable to open file: name = 'gadget_z0.500.0.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibility
    minor: Unable to open file
Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

**B.** then I compiled with `-DVR_HDF5=0` and `-DVR_PARTICLES_OUTSIDE_PERIOD_LIMIT=ON` and passed the gadget snapshots and got error in the `mpi domains`  
```
[0031] [  16.114] [error] mpiroutines.cxx:496 Particle outside the mpi domains of every process (1000,514.5870361,882.6102905)
```

**C.** I also converted one of the gadget snapshots to hdf5 and then use `-DVR_PARTICLES_OUTSIDE_PERIOD_LIMIT=ON` as in **A**, but got same result. 
```
[0028] [  15.136] [error] mpiroutines.cxx:MPIGetParticlesProcessor:L498 Particle outside the mpi domains of every process (986.3296509,1000,951.1694946)
```
Last thing I did was to run another simulation with the same box size (1000 Mpc/h) but with a smaller number of particles (512^3), and unfortunately I encountered the same issues. I am not entirely certain about the source of the error. I can share this data with you, so we can test simultaneously (it is a little bit less than 4GB), here is the [snapshot](https://cloud.iac.es/index.php/s/5qKYspkmHZbEAp5). 
thanks again!

**Comment by pelahi** [comment]
Hi @jegarfa , so I am curious how you read your snapshot data so that particles are not found to be at 1000.000. The code in VR just has 
```cpp
#ifdef GADGETDOUBLEPRECISION
#define FLOAT double
#else
#define FLOAT float
#endif
```
and reads the data using the following buffer 
```cpp
    FLOAT ctemp[3];
    Fgad[i].read((char*)&ctemp[0], sizeof(FLOAT)*3);
```
So the code by default is just reading 3 floats. It then converts them to doubles. Perhaps this is the issue but it still seems odd to me. Can you post your quick gadget reader check in period code?

**Comment by jegarfa** [comment]
Hi @pelahi,  sure. 
I read the snapshot in python, and basically, I look for the index where the particles have the same position as the box size. I made a mistake in my previous answer, I'm sorry, I actually found 13 particles with at least one of their coordinates the same as the box size. Here is a snippet of what I used (you can find the entire code in the folder I shared).
```
pos = readgadget.read_block(snapshot, "POS ", ptype=[1]) #positions in Mpc/h
BoxSize  = header.boxsize      #Mpc/h
idx_range_edge_box = np.where(pos[:,0] == BoxSize) # index of the particles with x-cordinate same as the boxsize
```

**Comment by pelahi** [comment]
Hi @jegarfa, okay good to know there are actually particles outside the periodic volume (or right at the edge). I have fixed a bug in the wrapping of periodic input and was not able to run the code on the input you provided. Can you try running it and also check to see if the results are sensible? I worry as it is a bit odd to find particles outside the expected volume for gadget input. I have encountered this before in RAMSES sims for star particles but not in gadget data. 

So try `git pull` and make again and see how it goes.

**Comment by jegarfa** [comment]
Hi @pelahi , thanks for the update!

I run this version of stf on the snapshots that I shared above and it completed the task. No complaints about out-of-domain particles. The "output.properties" files were written successfully. However, after writing these files I got a "minor" error related to hdf5.

This time I compile with `cmake -DVR_PARTICLES_OUTSIDE_PERIOD_LIMIT=ON ..` including hdf5-mpi (although I did not use it at all). 
I passed the snapshots in gadget format and expected ascii output (`Binary_output=0`). So I do not get why is looking for a hdf5 file. I will also run stf on the big simulation to cross validate. 
Here is the last part of the log file:

```
[0006] [ 229.990] [ info] substructureproperties.cxx:SortAccordingtoBindingEnergy:L5003 Done
[0002] [ 230.162] [ info] substructureproperties.cxx:SortAccordingtoBindingEnergy:L5003 Done
[0000] [ 230.161] [ [0003] [ 230.161] [ info] io.cxx:WriteProperties:L1651 [0004] [ 230.162] [ info] io.cxx:WriteProperties:L1651 Saving property data to /scratch/user/HALO/FOF_normal.properties.4
[0005] [ 230.162] [ info] io.cxx:WriteProperties:L1651 Saving property data to /scratch/user/FOF_HALO/FOF_normal.properties.5
[info] io.cxx:WriteProperties:L1651 Saving property data to /scratch/user/FOF_HALO/FOF_normal.properties.0
[0001] [ 230.162] [ info] io.cxx:WriteProperties:L1651 Saving property data to /scratch/user/FOF_HALO/FOF_normal.properties.1
[0002] [ 230.162] [ info] io.cxx:WriteProperties:L1651 Saving property data to /scratch/user/FOF_HALO/FOF_normal.properties.2
Saving property data to /scratch/user/FOF_HALO/FOF_normal.properties.3
[0006] [ 230.162] [ info] io.cxx:WriteProperties:L1651 Saving property data to /scratch/user/FOF_HALO/FOF_normal.properties.6
0007] [ 230.162] [ info] io.cxx:WriteProperties:L1651 Saving property data to /scratch/user/FOF_HALO/FOF_normal.properties.7
[0000] [ 233.181] [error] h5_utils.cxx:_hdf5_error_handler:L19 Error in HDF routine H5Fopen, aborting
HDF5-DIAG: Error detected in HDF5 (1.12.1) MPI-process 0:
  #000: H5F.c line 620 in H5Fopen(): unable to open file
    major: File accessibility
    minor: Unable to open file
  #001: H5VLcallback.c line 3501 in H5VL_file_open(): failed to iterate over available VOL connector plugins
    major: Virtual Object Layer
    minor: Iteration failed
  #002: H5PLpath.c line 578 in H5PL__path_table_iterate(): can't iterate over plugins in plugin path '(null)'
    major: Plugin for dynamically loaded library
    minor: Iteration failed
  #003: H5PLpath.c line 620 in H5PL__path_table_iterate_process_path(): can't open directory: /usr/local/hdf5/lib/plugin
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file
  #004: H5VLcallback.c line 3351 in H5VL__file_open(): open failed
    major: Virtual Object Layer
    minor: Can't open object
  #005: H5VLnative_file.c line 97 in H5VL__native_file_open(): unable to open file
    major: File accessibility
    minor: Unable to open file
  #006: H5Fint.c line 1990 in H5F_open(): unable to read superblock
    major: File accessibility
    minor: Read failed
  #007: H5Fsuper.c line 405 in H5F__super_read(): file signature not found
    major: File accessibility
    minor: Not an HDF5 file
Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

**Comment by pelahi** [comment]
Hi @jegarfa , what version and build of HDF5 are you using?

**Comment by jegarfa** [comment]
Hi @pelahi, I am using:
HDF5 v1.12.1 parallel - compiled with mpicc / gcc v10.1.0

**Comment by pelahi** [comment]
Hmm, so I'm using the same HDF5 version build with parallel and high level, api=112, so likely the same build you had. The only diff (and it shouldn't matter) is I had gcc/12.1.0 when testing your input and the resulting output. Are you sure this is just and HDF5 issue? Can you write the ascii output to the same directory?

**Comment by jegarfa** [comment]
Hi @pelahi, I apologize for the delay in getting back to you. 
It appears that the issue is directly linked to HDF5. For now I have tried the ffollowing:
1. **Output Directory:** I changed the output directory, to write the output to the same directory to the simulations or the stf executable, but I encountered the same issue.
2. **Ascii [0] and Binary Formats [1]:** I took a small simulation and specified ascii and binary output formats in the stf configuration file. The outcome remained the same - the files were  written, but the H5F error persisted.
3. **HDF5 output:** When specifying hdf5 outut in the configuration file this resulted in an even longer H5F error message.
Perhaps something is odd with my HDF5 module, I am not sure what. According to the `cmake` output HDF5 was detected successfully: `HDF5 Yes`, `Compressed HDF5 No`, `Parallel HDF5  Yes`.
Thanks!

**Comment by jegarfa** [comment]
Hi @pehali, 
This is just a little update. I made a fresh installation of stf in a different server and used the intel compilers with hdf5-1.12.2 and icpx 2022.2.0. Everything was fine with the compilation and detecting the libraries. After runing it with the test-simulation I got the error `h5_utils.cxx:_hdf5_error_handler:L19 Error in HDF routine H5Fopen, aborting`, the output is written, but I am not sure if it is complete.

**Comment by pelahi** [comment]
Hi @jegarfa, I tried producing output where each MPI rank writes their own files and also do collective writes. I am not having issues but I am using different compilers. So for completeness, 
```
$ g++ --version
g++ (GCC) 12.2.0 20220819 (HPE)
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
$ mpichversion
MPICH Version:    	3.4a2
MPICH Release date:	unreleased development copy
MPICH Device:    	ch4:ofi
MPICH configure: 	--prefix=/home/jenkins/install-gnu-ofi --without-mpe --enable-fortran=all --enable-shared --enable-sharedlibs=gcc --enable-debuginfo --enable-yield=sched_yield --enable-mpit-pvars=cray_mpiio_stat,cray_misc_stat --enable-g=mem --with-device=ch4:ofi --with-libfabric-include=/opt/cray/libfabric/1.15.0.0/include --with-libfabric-lib=/home/jenkins/pebuildenv/opt/libfabric/1.14.0-onlysockets/lib --with-custom-version-string=GTL-built-with,ROCM-5.0,CUDA-11.0 --with-namepublisher=file --with-shared-memory=sysv --with-ch4-shmmods=cray_xpmem --with-pmiext=pmi_cray_ext.h --with-pmi=cray --with-weak-pmiext=cray --disable-allowport --with-pm=gforker --with-file-system=ufs+lustre+cray+gpfs+nfs --disable-cxx --enable-threads=runtime --enable-thread-cs=global --enable-fast=O2
MPICH CC: 	/opt/gcc/9.1.0/bin/gcc -I/opt/cray/dvs/2.12_4.3.22-2.3_154.1__g7b1d0e31/include -I/opt/cray/pe/gtl/0.0.4.master/include  -D_CRAY_OFI -D_CRAY_CH4 -DHAVE_LUSTRE_COMP_LAYOUT_SUPPORT   -O2
MPICH CXX: 	CC
MPICH F77: 	ftn   -O2
MPICH FC: 	ftn   -O2
MPICH Custom Information: 	GTL-built-with,ROCM-5.0,CUDA-11.0
```

And the config (here shortened for brevity)
```
h5cc  -v
mpicc for MPICH version 8.1.25
Using built-in specs.
COLLECT_GCC=/opt/cray/pe/gcc/12.2.0/bin/../snos/bin/gcc
COLLECT_LTO_WRAPPER=/opt/cray/pe/gcc/12.2.0/snos/libexec/gcc/x86_64-suse-linux/12.2.0/lto-wrapper
Target: x86_64-suse-linux
Configured with: ../cpe-gcc-12.2.0-202211182106.97b1815c41a72/configure --prefix=/opt/cray/pe/gcc/12.2.0/snos --disable-nls --libdir=/opt/cray/pe/gcc/12.2.0/snos/lib --enable-languages=c,c++,fortran --with-gxx-include-dir=/opt/cray/pe/gcc/12.2.0/snos/include/g++ --with-slibdir=/opt/cray/pe/gcc/12.2.0/snos/lib --with-system-zlib --enable-shared --enable-__cxa_atexit --build=x86_64-suse-linux --with-ppl --with-cloog --disable-multilib
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 12.2.0 20220819 (HPE) (GCC)
```

I do have access to a system with the intel compiler so I'll give that a try and build hdf5 with that. Can you report here what you get with `h5cc -v`? Maybe there is something subtle there. 

Also, are you writing to a parallel filesystem? Like `lustre` or `gpFS` or `mooseFS`? Do they implemented some sort of striping? I am currently testing on a lustre filesystem with 
```
$ lfs -v 
lfs 2.15.0.4_rc2_cray_178_gf28cb6f
```
and the a striping of 
```
$ lfs getstripe output.properties.0
output.properties.0
lmm_stripe_count:  1
lmm_stripe_size:   1048576
lmm_pattern:       raid0
lmm_layout_gen:    0
lmm_stripe_offset: 0
	obdidx		 objid		 objid		 group
	     0	      85326035	    0x515f8d3	             0
```

Cheers,
Pascal

**Comment by pelahi** [comment]
Oh and a quick test to see if the hdf5 files are complete would just be to see if h5dump is happy. 
```bash
for file in output.*
do
  h5dump -H ${file}
done
```

**Comment by jegarfa** [comment]
Hi @pelahi,
 
I manage to run stf successfully with the simulation example and with hdf5 output (ASCII outputs still give me the mentioned error with hdf5).
The only thing I changed this time was the `.confile`. For all the previous tests I used a simple 3dfof taking as template the file `/examples/sample_dmcosmological_3dfof.cfg`, when using this file I got the error with hdf5 for any `Binary_output` (hdf5, ASCII and binary).

However, the error disappear if I use instead the example `sample_dmcosmological_3dfof_subhalo.cfg', in this case everything was fine with hdf5 output (in ASCII I got error).
I checked the completeness of the hdf5's and they look complete:

```
   DATASET "eig_xy" {
      DATATYPE  H5T_IEEE_F64LE
      DATASPACE  SIMPLE { ( 370 ) / ( 370 ) }
      ATTRIBUTE "Dimension_Length" {
         DATATYPE  H5T_IEEE_F32LE
         DATASPACE  SCALAR
      }
      ATTRIBUTE "Dimension_Mass" {
         DATATYPE  H5T_IEEE_F32LE
         DATASPACE  SCALAR
      }
      ATTRIBUTE "Dimension_Time" {
         DATATYPE  H5T_IEEE_F32LE
         DATASPACE  SCALAR
      }
      ATTRIBUTE "Dimension_Velocity" {
         DATATYPE  H5T_IEEE_F32LE
         DATASPACE  SCALAR
      }
   }
   DATASET "eig_xz" {
      DATATYPE  H5T_IEEE_F64LE
      DATASPACE  SIMPLE { ( 370 ) / ( 370 ) }
      ATTRIBUTE "Dimension_Length" {
         DATATYPE  H5T_IEEE_F32LE
         DATASPACE  SCALAR
      }
      etc.....
```

I was using the `sample_dmcosmological_3dfof.cfg` because a few months ago I run it without problems with the release version of stf using a different (old)simulation.
The only difference I find between these two example files are the flags for substructures; in other words, I got the hdf5 error if `Search_for_substructure=0` and `Halo_core_search=0`.
So, this makes me think that the hdf5 error is probably not related to the hdf5 library itself, but to an intermediate step that stf is looking for when doing after completing the 3dfof. I mean, it seems as if stf wants to write some files that were not created (maybe related to the substructre search?). 

---

btw, my `h5cc -v` output is: 

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/SIEvarios/gcc-10.1.0/libexec/gcc/x86_64-pc-linux-gnu/10.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc-10.1.0/configure --prefix=/opt/SIEvarios/gcc-10.1.0
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.1.0 (GCC) 
COMPILER_PATH=/opt/SIEvarios/gcc-10.1.0/libexec/gcc/x86_64-pc-linux-gnu/10.1.0/:/opt/SIEvarios/gcc-10.1.0/libexec/gcc/x86_64-pc-linux-gnu/10.1.0/:/opt/SIEvarios/gcc-10.1.0/libexec/gcc/x86_64-pc-linux-gnu/:/opt/SIEvarios/gcc-10.1.0/lib/gcc/x86_64-pc-linux-gnu/10.1.0/:/opt/SIEvarios/gcc-10.1.0/lib/gcc/x86_64-pc-linux-gnu/
LIBRARY_PATH=/opt/SIEvarios/gcc-10.1.0/lib/gcc/x86_64-pc-linux-gnu/10.1.0/:/opt/SIEvarios/gcc-10.1.0/lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../lib64/:/lib/x86_64-linux-gnu/:/lib/../lib64/:/usr/lib/x86_64-linux-gnu/:/opt/SIEvarios/gcc-10.1.0/lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-I' '/usr/include/hdf5/serial' '-Wdate-time' '-D' '_FORTIFY_SOURCE=2' '-g' '-O2' '-fdebug-prefix-map=/build/hdf5-X9JKIg/hdf5-1.10.0-patch1+docs=.' '-fstack-protector-strong' '-Wformat=1' '-Werror=format-security' '-v' '-L/usr/lib/x86_64-linux-gnu/hdf5/serial' '-mtune=generic' '-march=x86-64'
 /opt/SIEvarios/gcc-10.1.0/libexec/gcc/x86_64-pc-linux-gnu/10.1.0/collect2 -plugin /opt/SIEvarios/gcc-10.1.0/libexec/gcc/x86_64-pc-linux-gnu/10.1.0/liblto_plugin.so -plugin-opt=/opt/SIEvarios/gcc-10.1.0/libexec/gcc/x86_64-pc-linux-gnu/10.1.0/lto-wrapper -plugin-opt=-fresolution=/tmp/cc5HDRWm.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 /usr/lib/x86_64-linux-gnu/crt1.o /usr/lib/x86_64-linux-gnu/crti.o /opt/SIEvarios/gcc-10.1.0/lib/gcc/x86_64-pc-linux-gnu/10.1.0/crtbegin.o -L/usr/lib/x86_64-linux-gnu/hdf5/serial -L/opt/SIEvarios/gcc-10.1.0/lib/gcc/x86_64-pc-linux-gnu/10.1.0 -L/opt/SIEvarios/gcc-10.1.0/lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/opt/SIEvarios/gcc-10.1.0/lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../.. /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_hl.a /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.a -Bsymbolic-functions -z relro -lpthread -lsz -lz -ldl -lm -rpath /usr/lib/x86_64-linux-gnu/hdf5/serial -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /opt/SIEvarios/gcc-10.1.0/lib/gcc/x86_64-pc-linux-gnu/10.1.0/crtend.o /usr/lib/x86_64-linux-gnu/crtn.o

```

I am not sure about the parallel filesystem but I printed out the output of `lfs`:

```
$ lfs -v 
Try interactive use without arguments or use one of:
"setstripe"
"getstripe"
"setdirstripe"
"getdirstripe"
"mkdir"
"rm_entry"
"pool_list"
long etc.....
```

and 

```
$ lfs getstripe output.properties.0
lmm_stripe_count:  1
lmm_stripe_size:   1048576
lmm_pattern:       raid0
lmm_layout_gen:    0
lmm_stripe_offset: 41
	obdidx		 objid		 objid		 group
	    41	       2199921	     0x219171	             0

```

cheers,

**Comment by MatthieuSchaller** [comment]
I happen to face the exact same issue. However, I do not see `VR_PARTICLES_OUTSIDE_PERIOD_LIMIT` referenced anywhere in the code...

**Comment by pelahi** [comment]
Hi @MatthieuSchaller , it is not documented as the particular commit was a test. I'll add the documentation and can point to the specific changes required. It will take a bit as I am busy but will get to this asap.

**Comment by MatthieuSchaller** [comment]
I can fish out the changes myself if you can tell me which commit it is.

**Comment by pelahi** [comment]
Hi @MatthieuSchaller , so look at https://github.com/pelahi/VELOCIraptor-STF/commit/3cb55d0e7b4f446eec2800746f2305fe71e0283e (focus on io.h, CMakeLists.txt) and also https://github.com/pelahi/VELOCIraptor-STF/commit/85187e0c61ee06f4f6ec9051481a3ff41a91063f (where you can see the updates to gadetio.h running the periodic wrapping). I can do the same for HDF5 input to.

**Comment by MatthieuSchaller** [comment]
Thanks, that worked.

**Comment by pelahi** [comment]
Great! Glad it was quick to address :)
