### ISSUE TITLE
‘class H5::H5File’ has no member named ‘createAttribute’

### ISSUE THREAD

**Issue by DCunnama** [pelahi/VELOCIraptor-STF#13]
Hi Pascal,

I'm having an issue with the latest version. Getting the following error in making:

g++ -fopenmp -DUSEOPENMP -O2  -DSINGLEPRECISION -DLONGINT -DNOMASS -DLOWPRECISIONPOS -DGASON -DSTARON -DBHON -DSTRUCDEN -DOLDCCOMPILER -DGADGETLONGID -DGADGETDOUBLEPRECISION -DGADGETSINGLEMASSPRECISION -DGADGET2FORMAT -DEXTRASPHINFO -DEXTRASTARINFO -DEXTRABHINFO -DUSEHDF -I/anaconda3/include/ -I/home/cunnama/Code/VELOCIraptor-STF/stf//NBodylib//include/ -I/home/cunnama/Code/VELOCIraptor-STF/stf//include/ -I/include/ -c -o io.o io.cxx 
io.cxx: In function ‘void WriteProperties(Options&, Int_t, PropData*)’:
io.cxx:1090:19: error: ‘class H5::H5File’ has no member named ‘createAttribute’
io.cxx:1094:19: error: ‘class H5::H5File’ has no member named ‘createAttribute’
io.cxx:1099:19: error: ‘class H5::H5File’ has no member named ‘createAttribute’
io.cxx:1104:19: error: ‘class H5::H5File’ has no member named ‘createAttribute’
io.cxx:1109:19: error: ‘class H5::H5File’ has no member named ‘createAttribute’
io.cxx:1114:19: error: ‘class H5::H5File’ has no member named ‘createAttribute’
io.cxx:1119:19: error: ‘class H5::H5File’ has no member named ‘createAttribute’

I'm using hdf5-1.8.17-1

Any ideas?

Cheers,
Dan

**Comment by pelahi** [comment]
Hi Dan,
It could be that the hdf wasn't compiled with --enable-cxx. I am running
the current version of velociraptor with hdf 1.10 but I doubt its the
version and more likely the flags used to compile the hdf library.
Cheers,
Pascal

**Comment by DCunnama** [comment]
Hi Pascal, 

Right you are. Upgraded to 1.10 and rebuilt with 1.10.

Thanks,
Dan
