### ISSUE TITLE
Variables in .properties file

### ISSUE THREAD

**Issue by Fonotec** [pelahi/VELOCIraptor-STF#20]
Hi, I am running VELOCIraptor with SWIFT and I am currently basically understanding all the outputs of VELOCIraptor, so far a lot of the output is clear, but I have a few questions about what is going on with a few variables in properties.

So in general a lot of variables are called <something> and have an equivalent version which is called <something>_gas (like Xc and Xc_gas), so in the calculation of this variable are all the particle types used if there is no subscript _gas? or does this only include dm particles?

Furthermore I see there are a bunch of parameters called eig_ij with i,j = (x,y,z), are these the normalized eigenvectors corresponding to the velocity dispersion tensor which is given by the veldisp_ij elements?

When I run VELOCIraptor on a snapshot it finds that T_gas is zero in every halo, while if I calculate the temperature in my simulation it is definetly not zero. So is the aim of this variable to calculate the temperature of the gas or some other effective temperature property?

Lastly there are three variable names which are unclear, these are q, s and lambda_b, what physical property of the halo do these variables correspond to?

**Comment by pelahi** [comment]
Hi
For all variables without a subscript particle type, all particle types are
used to calculate the quantity. The eigen vector eig_ij are related to the
morphology of the reduced interia tensor whose eigenvalue ratios are q,s
(semi-major/major and minor/major). I will look into why T_gas=0 but it
should be non-zero if the self-energy of the gas has been loaded correctly.
You can look in substructureproperties.cxx for T_gas to see why this might
be the case. Finally q,s are the aforementioned eigenvalues and lambda_b is
the bullock spin parameter.

**Comment by Fonotec** [comment]
Hi, Thanks for your reaction. The zero temperatures were produced by a bug in the swift-interface. This has been fixed by James in the swift-interface.
