### ISSUE TITLE
Baryonic search

### ISSUE THREAD

**Issue by JBorrow** [pelahi/VELOCIraptor-STF#23]
Hi,

I am looking to run a baryon-only search (i.e. gas, stars, and BHs). I have looked through the documentation and it seems that it's only possible to run on _everything_, or on individual components. Is this currently possible within VELOCIraptor, and if not is it something you're open to adding?

Cheers,
Josh

**Comment by pelahi** [comment]
Hi Josh,
A baryon search is easy enough to implement as was something I was going to add. I do have a question regarding your use case. Did you want to link gas, stars, bh's using FOF only, or do you also want to identify galaxies and diffuse stellar components as described in http://adsabs.harvard.edu/abs/2018MNRAS.tmp.2604C 
I will be implementing additional searches to the master branch of velociraptor soon so that it will produce a galaxy catalog and link gas and black holes to the nearest tagged star particles. Is this use case what you are after?

**Comment by JBorrow** [comment]
Ah that looks perfect! Yes I was trying to use just the baryonic particles as a galaxy finder.

**Comment by pelahi** [comment]
Hi Josh,
There's a new bayronic search branch that can be used to run galaxy finding on star particles and then also assign gas particles and black hole particles to to the galaxy. I haven't fully tested it yet but feel free to have a look. This branch uses cmake so if you need guidance on what options you might want, just ask.

**Comment by JBorrow** [comment]
Hi, what configuration options do we need for that? Does it just do the galaxy finding automatically on top?

**Comment by pelahi** [comment]
Hi Josh, sorry for the late reply, the sample configuration options should work (see examples/sample_galaxyandbaryonscatalog_run.cfg). The only thing that you might run into that is an issue is if you are using HDF input or gadget input where baryonic properties have funny names/ unusual order. For HDF there are already several predefined naming conventions that you can access by editing the config file to include HDF_name_convention=1 (or what ever the appropriate number might be). The naming convention is outlined in hdfitems.h. Let me know if you run into issues reading input data

**Comment by JBorrow** [comment]
Hi,

Looks like this worked out of the box (with my SIMBA data). I'll get back to you with some more information once I've had a deeper look at the data.

Cheers!
Josh

**Comment by JBorrow** [comment]
Hi, at the moment this only appears to run a search on the stars; is there a way to include the dense gas (and black holes) that are part of these groups too?

**Comment by pelahi** [comment]
Hi Josh, if you can send me your config file and the output I might be able to decipher why the search didn't include gas and black holes. Are you using the extrabaryonsearch branch?

**Comment by JBorrow** [comment]
Hi, here's the script I'm using: https://github.com/JBorrow/simba-velociraptor-tools/blob/master/velociraptor_galaxy.cfg. In terms of output I've attached the groups file (which is tiny -- it only contains stars!) and the properties file. Let me know if you need any more info. I'm running this on SIMBA output, rather than SWIFT.

https://community.dur.ac.uk/joshua.borrow/dump/

P.S. sorry again for my slow reply
