### ISSUE TITLE
Segfault in sub-structure search of SWIFT-EAGLE box

### ISSUE THREAD

**Issue by MatthieuSchaller** [pelahi/VELOCIraptor-STF#33]
I am running the latest VR master on a low-redshift SWIFT-generated EAGLE 25 Mpc box.
My command line is 
```
stf -I 2 -i eagle_0142 -o catalog.hdf5 -C velociraptor_cfg.cfg
```
and I had configured VR with:
```
 cmake . -DCMAKE_CXX_FLAGS="-O3 -march=native -g" -DVR_MPI=OFF -DVR_USE_GAS=ON -DVR_USE_STAR=ON
```
The VR parameter file is https://gitlab.cosma.dur.ac.uk/swift/swiftsim/blob/master/examples/SantaBarbara/SantaBarbara-256/velociraptor_cfg.cfg with `Search_for_substructure` on line 28 set to 1.

The code runs smoothly until it crashes with a segfault. The last message printed to screen is 

```
0: finished calculation in 134.8474486
Total number of groups found is 5587
0: finished FOF search in total time of 685.7390322
TIME:: took 991224.7599 to search 103713803 with 48
Searching subset
0 Beginning substructure search 
```
Running in gdb, I get the following backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000500290 in SearchSubSub (opt=..., nsubset=nsubset@entry=103713803, Partsubset=..., pfof=@0x7ffffffed5e0: 0x7ffb328b9010, ngroup=@0x7ffffffed5d0: 5587, 
    nhalos=@0x7ffffffed5d8: 5587, pdata=<optimized out>) at /snap7/scratch/dp004/jlvc76/VELOCIraptor/VELOCIraptor-STF/src/search.cxx:2412
2412	                    while (pcsld->Phead[iindex++]!=Pval);
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7_6.5.x86_64 zlib-1.2.7-18.el7.x86_64
```

**Comment by pelahi** [comment]
I will have a look but I can at least check that the input makes sense. The code is searching all particle types loaded the same (does not differentiate between dark matter, gas, stars, etc) but is only loading gas and dark matter if present in the input file. It then proceeds to find 3DFOF halos and then search for substructures. It calculates FOF based masses before substructure is searched. All of this seems fine. 

I think the issue is a subtle one: an object has been decomposed entirely into substructures, leaving no parent object. I have encountered this before when searching for gas substructures, which would be happening here since the code is loading both dark matter and gas and is searching for both dm, dm+gas, and gas substructures. I have a catch at this point to make sure that if this is the case and nothing is left behind, it is handled but the rarity means perhaps this catch is not working. I might simply set the largest substructure is deemed to be the parent. 

But a question first: are you searching dm+gas? If not, and its a dm only sim, it is highly unusual for all particle to be associated with a substructure (can happen to unbind tidal radial shells but even this is very unlikely.

**Comment by MatthieuSchaller** [comment]
I think I am running with gas and stars substructure search. I compiled with VR_USE-GAS and VR-USE-STARS. The snapshot contains DM, stars and gas. My understanding is that the parameter file linked above is also demanding the decomposition of the baryons.

I can make the snapshot available if it helps.

**Comment by pelahi** [comment]
The best option for searching for dm+baryons is to treat the particles differently, such that FOF's are defined using dm but baryons are linked during the FOF process, substructures are phase-space dm and baryons associated to nearest dm particle in phase-space.

I had another look at the config file and I am a bit confused by what VR is doing. The config file is setup to load dm+gas, find 3DFOF halos and do not search for substructure but that is not what is happening. 

It would be useful to have a the .configuration file written by VR.

**Comment by MatthieuSchaller** [comment]
Here it is. :)
[catalog.configuration.hdf5.zip](https://github.com/pelahi/VELOCIraptor-STF/files/3299926/catalog.configuration.hdf5.zip)

**Comment by pelahi** [comment]
Oddly, this configuration file does indicate substructure should be searched for. But given the config file is setup to search all particles and also not unbind anything, then perhaps a substructure is being fully decomposed into smaller substructures. And my check for such an instance does not fully address this situation. 

Can you try a more standard dm+baryon config (see attached)? See if it seg faults.
[vr_hydro_3dfof_subhalos_test_config.txt](https://github.com/pelahi/VELOCIraptor-STF/files/3299968/vr_hydro_3dfof_subhalos_test_config.txt)

**Comment by MatthieuSchaller** [comment]
Unfortunately, that also crashed:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000500290 in SearchSubSub (opt=..., nsubset=nsubset@entry=106314752, Partsubset=..., pfof=@0x7fffffffb420: 0x7ffb294e1010, ngroup=@0x7fffffffb410: 5909, 
    nhalos=@0x7fffffffb418: 5909, pdata=<optimized out>) at /snap7/scratch/dp004/jlvc76/VELOCIraptor/VELOCIraptor-STF/src/search.cxx:2412
2412	                    while (pcsld->Phead[iindex++]!=Pval);
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7_6.5.x86_64 zlib-1.2.7-18.el7.x86_64
```

I ran `/stf -I 2 -i eagle_0142 -o catalog.hdf5 -C vr_hydro_3dfof_subhalos_test_config.txt`

**Comment by pelahi** [comment]
Hmm, I wonder if there is something subtle with the swift hydro and master. Perhaps I introduced something when trying to add in swift stuff. Perhaps you can try running the expandedproperties branch of VR as that is working with eagle input and producing a bunch of hydro properties.

The config needs to be updated as now when analysing a hydro sim, more reference units are required. I've attached a config that should work (tested on eagle input). 
[vrconfig_3dfof_subhalos_bound_hydro.txt](https://github.com/pelahi/VELOCIraptor-STF/files/3301684/vrconfig_3dfof_subhalos_bound_hydro.txt)

And maybe you can grant me access to the swift eagle file.

**Comment by MatthieuSchaller** [comment]
You can get the snapshot from here:
 http://virgodb.cosma.dur.ac.uk/swift-webstorage/eagle_0142.hdf5 (13GB)

I'll try the other branch, thanks.

**Comment by MatthieuSchaller** [comment]
That seems to be fixed now with all the recent updates to the code. Thanks!
