### ISSUE TITLE
Error, net size 0 with row,col=0,0

### ISSUE THREAD

**Issue by DCunnama** [pelahi/VELOCIraptor-STF#4]
Hi Pascal,

Still having the same issue with the following calculation:

Now get average in grid cell and find outliers

I've included the makefile, config and output:

Thanks,
Dan

[velociraptor.tar.gz](https://github.com/pelahi/VELOCIraptor-STF/files/723416/velociraptor.tar.gz)

**Comment by pelahi** [comment]
weirdly this seems like either the local velocity density calculation is
failing or the center of mass and the mean halo velocity is off.
Maybe try
Search_for_substructure=0
FoF_Field_search_type=5
just to see if the properties it calculates for the halo make sense.
The next thing to try is
Search_for_substructure=1
Output_den=1
with the STRUCDEN compile flag off along with HALODEN
then check
the file
your_output_filename.localden
to see if these are positive floats.

**Comment by DCunnama** [comment]
Ok, so it doesn't look like the properties make sense, getting negative masses.

[snap_m25n256.snap_134.VELOCIraptor.properties.tar.gz](https://github.com/pelahi/VELOCIraptor-STF/files/723580/snap_m25n256.snap_134.VELOCIraptor.properties.tar.gz)

**Comment by pelahi** [comment]
I wonder if this is an issue with the Endian of the dataset. Does the input
look fine in hdfview (or h5dump)? I'm a bit careless when checking the
endian of input data.

**Comment by DCunnama** [comment]
Hdf5 by construction should remove any endian issues from within the library.

But as it is, the fact that its reading everything else fine, the velocities and positions, and even the masses look reasonable, with the exception of the negative.

The massed are stored in a Mass block not in the mass table, but that shouldn't be an issue should it?

**Comment by pelahi** [comment]
It shouldn't be an issue. Could you add after line 483 in hdfio.cxx (which
as LN=)
cout<<hdf_header_info[ifirstfile].mass[1]<<" "<<mscale<endl;
and compile. See if, for reasons that still aren't clear to me, one of
these is negative?

**Comment by DCunnama** [comment]
0 1.470588235

**Comment by pelahi** [comment]
so the mass header for DM is zero? Is that correct?
what about at line 763 adding in
cout<<ifloat<<" "<<floatbuff[0]<<" <<doublebuff[0]<<endl;
so you can see what it s reading in the mass data set.

**Comment by DCunnama** [comment]
Yeah, the mass header is 0, that's correct.

Seems that floatbuff[0] i the issue:

1 -35102.88281 0.68

**Comment by pelahi** [comment]
Which value seems correct? I would expect 0.00776 (1e10 Msun/h). Neither is
what I would expect for a 25 Mpc/h 256^3 simulation.
Are the units solar masses? or 1e10 solar masses? The code thinks the data
space contains float32 but does h5dump think the data type is a float64? Or
float 32?

Oh and I noticed that you have units of G that would be 1e10 Msun, kpc, and
km/s but you have Hubble in km/s/Mpc (should be 0.1 for km/s/kpc).

**Comment by DCunnama** [comment]
None of them seem correct, the Mass of the DM particles is 0.0065132.

I see the units were incorrect, I've corrected them now. We're in kpc and 1e10 Msol:

Units: L=0.001, M=1e+10, V=1, G=43021.1

Anyway, I'm still getting the same value read in:

1 -35102.88281 0.68

The datatype is H5T_IEEE_F32LE

**Comment by pelahi** [comment]
so then it should try to read a float as the code is doing. Is the hdf file
somewhere I could get access to so I can see why it is loading in this
negative value?

**Comment by DCunnama** [comment]
Thanks Pascal, 

I stuck the file on castor: /home/nifty2014/ClustersOfGalaxies/PLAYGROUND/dcunnama/data/

Sorry about this.

**Comment by pelahi** [comment]
I know what is the issue, DM particles in illustris format don't have a
masses data set
        names[itemp++]=H5std_string("Coordinates");
        names[itemp++]=H5std_string("Velocities");
        names[itemp++]=H5std_string("ParticleIDs");
        if (hdfnametype==HDFILLUSTISNAMES) {
            names[itemp++]=H5std_string("Potential");

So you should add
       names[itemp++]=H5std_string("Masses");
after line 186. Fix everything

**Comment by DCunnama** [comment]
Ha, bingo.

Sorry I didn't see that sooner.

Thanks, seems to be reading properly now.
