### ISSUE TITLE
Star formation rates in EAGLE/SWIFT

### ISSUE THREAD

**Issue by JBorrow** [pelahi/VELOCIraptor-STF#43]
Currently start formation rates are calculated as sum(sfr_of_particles_in_x). This is incorrect, as the particle data carries the following (in postprocessing):

+ If positive: current star formation rate
+ If negative: the last time at which the gas particle was star forming.

This leads to massively negative reported star formation rates for many gas properties.

**Comment by pelahi** [comment]
Hi @JBorrow  @MatthieuSchaller this is easy enough to fix so that all particles that have sfr<0 are set to zero but do we want to keep this information as well?

**Comment by MatthieuSchaller** [comment]
No, not in the halo catalogues.
