### ISSUE TITLE
Segmentation fault in MPIBuildParticleNNImportList if VR_NO_MASS=ON

### ISSUE THREAD

**Issue by jchelly** [pelahi/VELOCIraptor-STF#46]
I'm running Velociraptor on the EAGLE 100Mpc DMONLY box and also on a similar simulation run with Swift. In both cases I have problems if I set VR_NO_MASS=ON in cmake. The program crashes at line 1631 of mpiroutines.cxx:
```
                PartDataIn[nexport]=Part[index];
```
The value of nexport seems to be out of range - it's slightly larger than the total number of particles in the simulation. I think maybe the search radius is computed incorrectly in this case because NNDataGet[i].R2 is ~1000. Assuming this is radius squared in Mpc/h units, that would be a search radius of about twice the box size. Maybe the particle mass isn't taken into account correctly when calculating r200 if VR_NO_MASS=ON? If I set VR_NO_MASS=OFF then I don't get a crash.

**Comment by pelahi** [comment]
This is quite likely as I've been neglecting making sure VR_NO_MASS works and focusing on adding other functionality. I'll address this.

**Comment by pelahi** [comment]
I have updated the NO_MASS VR and it seems to work. More extensive tests to follow but now the major updates are folded into master.
