### ISSUE TITLE
Mass-weighted stellar ages for subhaloes

### ISSUE THREAD

**Issue by MatthieuSchaller** [pelahi/VELOCIraptor-STF#47]
One feature that would be great is to have the mass-weighted stellar ages of the subhaloes. 

It shouldn't be too hard to implement (happy to do it) but we should agree on what is the best way to do so. SWIFT currently stores the birth scale factor of each star. So to get ages we need to make some cosmological calculation. Alternatively, we could change the birth times stored in SWIFT to be "time since the Big Bang". That would be different from what we did in EAGLE but may actually be easier in general. 

What do you think?

**Comment by ymbahe** [comment]
In principle, I think that storing the actual birth time (age of the Universe) instead of birth scale factor in SWIFT would be the best solution. I'm just wondering whether it would be more confusing overall, especially if the time is written in internal units (~1 Tyr)...?

**Comment by pelahi** [comment]
Currently, VR converts scale factors to ages using the cosmology. It does require assuming standard cosmological models well parameterised by radiation, matter, cosmological constant and curvature (assuming flat). This can be expanded to take into account more constituents.

**Comment by pelahi** [comment]
This can now be done by loading the stellar ages field to get mass weighted average, logaverage, standard deviation, etc.
