### ISSUE TITLE
Aliased buffers in MPI_Allreduce in hdfio.c and use of possibly uninitialized variable MP_DM

### ISSUE THREAD

**Issue by jchelly** [pelahi/VELOCIraptor-STF#48]
At line 2230 of hdfio.cxx we have
```
    if (opt.nsnapread>1) {
        MPI_Allreduce(&MP_DM,&MP_DM, 1, MPI_DOUBLE, MPI_MIN,mpi_comm_read);
    }
```
Intel MPI crashes on this because the send and receive buffers overlap. It's easily fixed by replacing the send buffer with MPI_IN_PLACE.

However, it looks like MP_DM is only set if we compile with -DHIGHRES, which I'm not using so it probably shouldn't execute this line at all. Maybe this should be in a #ifdef HIGHRES?

There's another possible use of MP_DM when it hasn't been set at line 2209:
```
        opt.Omega_b=MP_B/(MP_DM+MP_B)*opt.Omega_m;
```

**Comment by pelahi** [comment]
Fixed by adding the MPI_IN_PLACE and wrapping the call in an ifdef
