### ISSUE TITLE
Metadata output

### ISSUE THREAD

**Issue by JBorrow** [pelahi/VELOCIraptor-STF#49]
Currently, velociraptor writes a number of text files containing metadata. It would be really helpful if the contents of these files (.siminfo in particular) were added to the HDF5 .properties output.

Alongside this, it would be incredibly useful to have the boxsize added as an attribute in the .properties output.

**Comment by pelahi** [comment]
Currently the properties file does have the box size, scale factor and unit conversions in the attributes. However, I could add a more complete list, including full cosmology, simulation info, units as separate groups in the HDF5 output along with the configuration options. I will try to implement this soon.

**Comment by JBorrow** [comment]
Was this box-size added recently? I can't seem to find it in any of my properties catalogues.

**Comment by JBorrow** [comment]
Something else here is that the units aren't particularly consistent. For instance, stellar ages are given in one unit, which is inconsistent with the time specified by the length and velocity unit. Star formation rate is again inconsistent with the mass and time units... Perhaps this is desirable as it makes the catalogues more human-readable but it can be confusing for some properties.

**Comment by pelahi** [comment]
I'll add the extra meta information but I think I will leave the units as is, as they are more human-readable. However, I could provide a second set that is fixed to make all the units consistent (conversion to cgs say). As for the box size, this is given by 'Period'.

**Comment by JBorrow** [comment]
Ah ok! In that case, I think there is some h-factor stuff going on there. This is a SWIFT run, and it's saying that the boxsize is 36 Mpc, which is ~ 25 / 0.7 Mpc.

**Comment by pelahi** [comment]
The period is for that time and is in physical units. Period = 25 Mpc *a = 25 *0.14 = 3.6. 
Also, I've just pushed a new branch with more meta information written to the properties file. I haven't tested it yet and will add more info but if you don't mind, have a [go](https://github.com/pelahi/VELOCIraptor-STF/tree/feature/extrametainfo)

**Comment by pelahi** [comment]
Meta branch merged into master
