### ISSUE TITLE
Problems with `Gas_chemistry_names` and `Gas_internal_property_names` configuration variables

### ISSUE THREAD

**Issue by wmfw23** [pelahi/VELOCIraptor-STF#58]
Some issues getting VELOCIraptor to output Gas properties for SWIFT-like simulation outputs.

- `Gas _chemistry _names` doesn't seem to work with SWIFT-like outputs: The SWIFT outputs have a single array for element abundances, `ElementMassFractions`, where columns represent different elements, specified in the header. Specifiying individual elements eg `Gas_chemistry_names=MassFractionsCarbon,MassFractionsOxygen` crashes as these fieldnames do not exist in the output `properties` file, while specifiying `Gas_chemistry_names=ElementMassFractions,` returns a single element for each halo in the outputs (perhaps the Hydrogen mass fraction as values consistently ~0.7). Instead, returning a 2D array with the mass-weighted sum of elements in each respective column would be ideal. 

- Also, setting `Gas_chemistry_names` and  `Gas_internal_property_names` with single elements instead of lists runs no matter what the input, but returns nothing in the output files (e.g. `Gas_chemistry_names=ElementMassFractions` without the trailing comma will run but no `ElementMassFractions` array in the output `properties` file). 

- Related, If a trailing comma is missed from the end of list for these variables, the last element is also missed with no warning (*not sure this is technically a bug*). 

-  Finally when supplying a list to `Gas_internal_property_names`, In the output these properties seem to come out identical, e.g. with `Gas_internal_property_names=ParticleIDs,Pressures,` as a stupid example, the `properties` file contains `ParticleIDs_gas` and `Pressures_gas`, but these arrays are equivalent. I *think* it is the `Pressures` (i.e. last element in the list) that is being replicated here.

**Comment by pelahi** [comment]
I will add updates so that users can also provide an index specifying where in the named array values need to be retrieved from and also change the bulk property calculated for that quantity. 
I can improve the parser but trailing comma is currently needed for the fields as the comma is used as a delimiter. 
Last point: not certain why the replication but I will look into it.

**Comment by MatthieuSchaller** [comment]
For the chemistry, we actually store the name - index matching in the snapshots. This can be read from the header and so no need to hardcode anything if at a later stage we add an element (or remove one) from the SWIFT model.

**Comment by MatthieuSchaller** [comment]
BTW, I can give you a hand with these if necessary.

**Comment by pelahi** [comment]
Hi @wmfw23 , I now have a working branch to load in arbitrary elements and calculate averages (or log average, total, std, log std or all of the above, mass weighted or not). I'm just running it through travis to fix any bugs. I need to update the documentation and examples. The branch is in https://github.com/pelahi/VELOCIraptor-STF/tree/feature/generalcalculations if you want to have a look.

**Comment by pelahi** [comment]
Now integrated feature/generalcalculations which contains features: read in a specific column from a 2d array; calculate variety of properties based on config options.

**Comment by wmfw23** [comment]
Great, seems to be working nicely from current tests.
