### ISSUE TITLE
Missing property from documentation: Parent_halo_ID

### ISSUE THREAD

**Issue by VictorForouhar** [pelahi/VELOCIraptor-STF#61]
In the VELOCIraptor's (v1.51) `.catalog_groups` output file, there is a property named `Parent_halo_ID`, but I have not managed to find any information or mention of it in the documentation. 

I checked whether it was the same as the `hostHaloID` property contained in the output `.properties`, but they are different.

**Comment by VictorForouhar** [comment]
I think I figured out what information `Parent_halo_ID` contains. Whereas `hostHaloID` points to the top level, field halo (`structureType == 10`) that a group is bound to, the property `Parent_halo_ID` points to the halo (not necessarily `structureType == 10`) a group is part of as substructure, allowing you to determine the group hierarchy. Is this correct? 

In either case, I still think it would be useful to mention this in the documentation.

**Comment by pelahi** [comment]
Correct, this field contains the information to the full substructure hierarchy, indicating an objects immediate parent. I will update the documentation.

**Comment by MatthieuSchaller** [comment]
@VictorForouhar how about the other aspects you were wondering about? Have these yet been clarified?

**Comment by VictorForouhar** [comment]
@MatthieuSchaller In regards to the results I was getting with VELOCIraptor, I still haven't run some of the tests I had in mind, as COSMA is down for maintenance at the moment. 

Once I get the chance, I would want to run another halo finder and see whether I get the same results as with VELOCIraptor. If I do, this might mean it has something to do with the data I am using and not an issue with VELOCIraptor itself (which I want to confirm before potentially flagging an issue).

**Comment by MatthieuSchaller** [comment]
Keep in mind that all the halo finders have different definitions of what a 'halo' is and diverge even more in terms of their definition of what a sub-halo is. See https://ui.adsabs.harvard.edu/abs/2012MNRAS.423.1200O/abstract
