### ISSUE TITLE
VR doesn't link stars to the halos in some snapshots

### ISSUE THREAD

**Issue by Fonotec** [pelahi/VELOCIraptor-STF#65]
For runs I did with a fork of swift, the COLIBRE fork I have been running some boxes. In these boxes I form stars and I can see the stars if I look at the snapshot with for example gadgetviewer I see that there are stars that are in the halos. However when I run VR on the snapshot it does halo finding and that seems to work (like the HMF is correct), but when I start to look at properties related to stars it seems to produce results that do not make sense, stellar masses way too low etc. I expect to get a similar result as compared to the other boxes with the swift main code.  

Physical the simulation is very similar to the EAGLE XL runs done by other people I only use a different fork of SWIFT and I have some additional extra arrays in the hdf5 file for the gas particles. 
The snapshot can be found on cosma in directory `/cosma6/data/dp004/dc-nobe1/swift-colibre/examples/EAGLE_ICs/EAGLE_25_NOAGN_exp`, I run VR on eagle_0036.hdf5 in this folder using the `vrconfig_3dfof_subhalos_SO_hydro.cfg` file (not on the fly). I also tried running without substructure finding but also in this case the result seem to be similar in terms of not getting good stellar masses. 

I guess there is a subtle thing going on, I checked the units between the fields in the snapshots and that seem to be the same as in the main swift code, so I do not know what is happening.

**Comment by pelahi** [comment]
Hi @Fonotec , I cannot access the directory you list. Can you please place this snapshot somewhere else?

**Comment by Fonotec** [comment]
Hi @pelahi, I place the snapshot in the directory `/cosma6/data/dp004/dc-nobe1` together with the cfg file, can you access the file now?

**Comment by pelahi** [comment]
Hi @Fonotec , I don't have access to `/cosma6/. I do have access to `/cosma7/data/dp004/`

**Comment by Fonotec** [comment]
Hi @pelahi, I put the files in `/cosma7/data/dp004/dc-nobe1`.

**Comment by pelahi** [comment]
Seems that the input files had starts dithered at different position.

**Comment by MatthieuSchaller** [comment]
Yes, agreed. That's fixed on our side.
