### ISSUE TITLE
Incorrect check for Mass_value in config file when using NO_MASS

### ISSUE THREAD

**Issue by jchelly** [pelahi/VELOCIraptor-STF#89]
If the velociraptor development branch is compiled with -DNO_MASS it insists on having the Mass_value parameter in the config file even when it should be getting the mass value from elsewhere (e.g. read from a HDF5 snapshot or passed in from Swift).

Runs which previously worked with master now abort with
```
Code compiled to not store mass per particle. Valid Mass_value in the config must be passed.
```
Maybe this could be fixed by doing the opt.MassValue<=0 test later, once the particle mass is known.

**Comment by pelahi** [comment]
I will update this by having the check later in the code.

**Comment by pelahi** [comment]
@jchelly, I have a branch https://github.com/pelahi/VELOCIraptor-STF/tree/update/nomasscheck, which has a check when compiled with NOMASS that occurs after data is loaded (from swift or from hd5/gadget inputs). Please let me know if you are happy with this update. If so, I will merge with development (and then master).

**Comment by jchelly** [comment]
That has fixed the problem on the Eagle HDF5 snapshot I was trying to run on.
